server:
  port: 10086 #服务端口
spring:
  application:
    name: eurekaserver #eureka的服务名称
eureka:
  client: #eureka的地址信息，要是有多个以逗号隔开
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka